spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qr_system?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: cwj040812

    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show_sql: true
  mail:
    host: smtp.qq.com
    username: 4682695530@qq.com
    password: nxvoeglbdhstbgfc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true  # 打开调试日志，帮助排查问题
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
mybatis:
  # 指定相应接口对应的xml文件所在目录
  mapper-locations: classpath:mapper/*.xml
  # 实体类所在包
  type-aliases-package: top.wujiangcai.springboot.database.entity

  configuration:
    # mybatis开启驼峰命名
    map-underscore-to-camel-case: true
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

myapp.jwt:
  secret: "helloworld"
  expiration: 3600000  # 单位为毫秒（1小时）


aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com # 你的OSS服务地址
    accessKeyId: LTAI5tDYXXW6uUmGneBixhHQ # 你的Access Key ID
    accessKeySecret: v4M5UmFXZc9HtOFDKR6y06Y1MZRFxy # 你的Access Key Secret
    bucketName: my-bucket-621 # 你的Bucket名称
